# Create a default.json environment file under config/ folder
# Add Environment Variables from Repository Secrets
name: Create env file
on: 
  push:
    branches:
      - master

jobs:
  run:
    name: Create env file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create default.json file
        run: |
          echo -n "" > config/default.json
          cat <<EOT >> config/default.json
          {
            "server": {
              "secret": ${{secrets.A_SECRET}}
            }
          }
          EOT
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Pramod AJ
          author_email: avj2352@gmail.com
          message: 'Adding Environment file'
          add: '*.json'
